site_name: Literature Archive

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share

nav:
  - Home: index.md
  - Authors: authors/index.md

plugins:
  - search:
      lang:
        - en
        - zh
  
extra:
  search:
    language: en
    placeholder: "搜索作者 / 文献…"
    